import {keyMirror} from 'App/Lib/Utils/Utils';
export default keyMirror([
  'SET_PLATFORM',
  'SET_VERSION',

  'SESSION_TOKEN_REQUEST',
  'SESSION_TOKEN_SUCCESS',
  'SESSION_TOKEN_FAILURE',

  'DELETE_TOKEN_REQUEST',
  'DELETE_TOKEN_SUCCESS',

  'ON_LOGIN_STATE_CHANGE',
  'LOGOUT',

  'ON_AUTH_FORM_FIELD_CHANGE',
  'SIGNUP_REQUEST',
  'SIGNUP_SUCCESS',
  'SIGNUP_FAILURE',

  'LOGIN_REQUEST',
  'LOGIN_SUCCESS',
  'LOGIN_FAILURE',

  'LOGOUT_REQUEST',
  'LOGOUT_SUCCESS',
  'LOGOUT_FAILURE',

  'LOGGED_IN',
  'LOGGED_OUT',

  'SET_SESSION_TOKEN',

  'RESET_PASSWORD_REQUEST',
  'RESET_PASSWORD_SUCCESS',
  'RESET_PASSWORD_FAILURE',

  'GET_PROFILE_REQUEST',
  'GET_PROFILE_SUCCESS',
  'GET_PROFILE_FAILURE',

  'ON_PROFILE_FORM_FIELD_CHANGE',

  'PROFILE_UPDATE_REQUEST',
  'PROFILE_UPDATE_SUCCESS',
  'PROFILE_UPDATE_FAILURE',

  'SET_STATE',
  'GET_STATE',
  'SET_STORE',

  'FORGOT_PASSWORD',
  'LOGIN',
  'REGISTER'

])
